services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
    ports:
      - "5432:5432"

  app:
    build: .
    command: ["python","-m","src.pipelines.run_pipeline"]
    volumes:
      - .:/app
